root: true
env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - application
  - plugin:storybook/recommended
overrides:
  - files:
      - '*.stories.@(ts|tsx|js|jsx|mjs|cjs)'
    rules:
      storybook/hierarchy-separator: error
      storybook/default-exports: off
      import/no-extraneous-dependencies: off
